// Config domain: rendering. Owned by lane R (render).
// V4 — every render tunable carries unit/owner/default/range/tier. No magic numbers in engine code.
// V25 — capability thresholds are expressed as per-tier minimum adapter limits: the tier-resolution
// machinery (resolve(spec, tier)) gives the minimum a GPU must report to QUALIFY for that tier.

import { num, bool } from '../spec';
import { registerDomain } from '../registry';

export const renderingConfig = registerDomain('rendering', {
  // ---- V25 capability gates (R15 GPU adapter limits) ----
  // For each tier we resolve the MINIMUM adapter limit required to be eligible for that tier.
  // detectQualityTier picks the highest tier whose every minimum is satisfied; mobile = floor.
  minMaxTextureDimension2D: num({
    owner: 'rendering',
    unit: 'count',
    doc: 'Minimum GPUSupportedLimits.maxTextureDimension2D required to qualify for a tier (V25/R15).',
    default: 4096, // mobile-webgpu floor
    min: 2048,
    max: 32768,
    integer: true,
    tiers: { 'desktop-high': 16384, 'desktop-medium': 8192, 'desktop-compat': 8192, 'mobile-webgpu': 4096 },
  }),
  minMaxBufferSize: num({
    owner: 'rendering',
    unit: 'bytes',
    doc: 'Minimum GPUSupportedLimits.maxBufferSize required to qualify for a tier (V25/R15).',
    default: 134217728, // 128 MiB mobile floor
    min: 67108864,
    max: 8589934592,
    integer: true,
    tiers: {
      'desktop-high': 1073741824, // 1 GiB
      'desktop-medium': 536870912, // 512 MiB
      'desktop-compat': 268435456, // 256 MiB
      'mobile-webgpu': 134217728, // 128 MiB
    },
  }),
  minMaxComputeWorkgroupStorageSize: num({
    owner: 'rendering',
    unit: 'bytes',
    doc: 'Minimum GPUSupportedLimits.maxComputeWorkgroupStorageSize required to qualify for a tier (V25/R15).',
    default: 16384, // mobile floor (WebGPU spec minimum)
    min: 16384,
    max: 65536,
    integer: true,
    tiers: {
      'desktop-high': 32768,
      'desktop-medium': 32768,
      'desktop-compat': 16384,
      'mobile-webgpu': 16384,
    },
  }),

  // ---- V25 startup micro-benchmark gates (measured perf, NOT browser name) ----
  // detectTierFromProbe combines these with the adapter-limit gates above: a device qualifies for a
  // tier only if it BOTH satisfies that tier's minimum adapter limits AND its measured probe frame is
  // within budget AND its measured fill-rate score clears the floor. Measured perf can only DEMOTE
  // below the limit ceiling, never promote above it. Below the mobile floor → explicit error (V4).
  probeGpuFrameBudgetMs: num({
    owner: 'rendering',
    unit: 'ms',
    doc: 'Max measured GPU frame time (ms) at the fixed reference probe scene to qualify for a tier (V25).',
    default: 24, // mobile-webgpu ceiling — slower than this fails every tier
    min: 1,
    max: 100,
    tiers: {
      'desktop-high': 6,
      'desktop-medium': 10,
      'desktop-compat': 16,
      'mobile-webgpu': 24,
    },
  }),
  probeMinFillRateScore: num({
    owner: 'rendering',
    unit: 'ratio',
    doc: 'Min measured device-independent fill/throughput score from the startup probe to qualify for a tier (V25).',
    default: 10, // mobile floor
    min: 0,
    max: 1000,
    tiers: {
      'desktop-high': 100,
      'desktop-medium': 60,
      'desktop-compat': 30,
      'mobile-webgpu': 10,
    },
  }),

  // ---- Output / frame ----
  pixelRatioMax: num({
    owner: 'rendering',
    unit: 'ratio',
    doc: 'Upper clamp on devicePixelRatio applied to the renderer (V22 scaling order).',
    default: 1.5,
    min: 0.5,
    max: 3,
    tiers: { 'desktop-high': 2, 'desktop-medium': 1.5, 'desktop-compat': 1, 'mobile-webgpu': 1.5 },
  }),

  // ---- Crowd instancing (T9 / V2) ----
  crowdInstanceCapacity: num({
    owner: 'rendering',
    unit: 'count',
    doc: 'Fixed capacity of the GPU instance buffer for the crowd InstancedMesh (V2/V10).',
    default: 2000,
    min: 64,
    max: 20000,
    integer: true,
    tiers: { 'desktop-high': 4000, 'desktop-medium': 2000, 'desktop-compat': 1000, 'mobile-webgpu': 500 },
  }),
  crowdVariationCount: num({
    owner: 'rendering',
    unit: 'count',
    doc: 'Number of distinct per-instance visual variation seeds for crowd diversity (T9).',
    default: 16,
    min: 1,
    max: 256,
    integer: true,
  }),
  crowdInstanceScaleMin: num({
    owner: 'rendering',
    unit: 'ratio',
    doc: 'Lower bound of per-instance scale variation applied during SoA->instance packing.',
    default: 0.9,
    min: 0.5,
    max: 1,
  }),
  crowdInstanceScaleMax: num({
    owner: 'rendering',
    unit: 'ratio',
    doc: 'Upper bound of per-instance scale variation applied during SoA->instance packing.',
    default: 1.1,
    min: 1,
    max: 2,
  }),
  // ---- Crowd GPU-compute transform/animation (T9 / V2 GPU-readable animation data) ----
  crowdAnimPhaseSpeed: num({
    owner: 'rendering',
    unit: 'hz',
    doc: 'Cycles/sec the crowd compute shader advances each instance animation phase (drives the walk bob).',
    default: 1.4,
    min: 0,
    max: 8,
  }),
  crowdAnimBobMeters: num({
    owner: 'rendering',
    unit: 'meters',
    doc: 'Peak vertical bob amplitude applied per instance from the GPU-advanced animation phase.',
    default: 0.06,
    min: 0,
    max: 1,
  }),
  crowdVariationBrightnessSpread: num({
    owner: 'rendering',
    unit: 'ratio',
    doc: 'Per-instance shader brightness spread (+/-) around the base crowd colour, keyed by variation seed.',
    default: 0.2,
    min: 0,
    max: 0.9,
  }),

  // ---- Device-loss recovery (V23) ----
  deviceLossMaxRecoveries: num({
    owner: 'rendering',
    unit: 'count',
    doc: 'Max automatic WebGPU device-loss recoveries before session-safe shutdown (V23).',
    default: 3,
    min: 0,
    max: 10,
    integer: true,
  }),

  // ---- Crowd render paths (T30 / V2): hero / instanced / horde-LOD / impostor selected by tier+distance ----
  crowdHeroBudget: num({
    owner: 'rendering',
    unit: 'count',
    doc: 'Max simultaneously promoted hero (skinned-mesh) zombies — detailed hero band (V13/§V-gates 20-40).',
    default: 30,
    min: 0,
    max: 120,
    integer: true,
    tiers: { 'desktop-high': 40, 'desktop-medium': 30, 'desktop-compat': 16, 'mobile-webgpu': 8 },
  }),
  crowdHeroMaxDistanceMeters: num({
    owner: 'rendering',
    unit: 'meters',
    doc: 'Beyond this distance a hero-tier zombie is downgraded to the instanced animated path.',
    default: 18,
    min: 1,
    max: 200,
    tiers: { 'desktop-high': 24, 'desktop-compat': 12, 'mobile-webgpu': 9 },
  }),
  crowdInstancedMaxDistanceMeters: num({
    owner: 'rendering',
    unit: 'meters',
    doc: 'Beyond this distance the instanced animated path downgrades to the horde-LOD path.',
    default: 45,
    min: 2,
    max: 400,
    tiers: { 'desktop-high': 60, 'desktop-compat': 32, 'mobile-webgpu': 24 },
  }),
  crowdHordeLodMaxDistanceMeters: num({
    owner: 'rendering',
    unit: 'meters',
    doc: 'Beyond this distance the horde-LOD path downgrades to the far impostor/cluster path.',
    default: 110,
    min: 4,
    max: 800,
    tiers: { 'desktop-high': 150, 'desktop-compat': 80, 'mobile-webgpu': 55 },
  }),
  crowdMaterialFamilyCount: num({
    owner: 'rendering',
    unit: 'count',
    doc: 'Number of shared crowd material families (flesh/clothing/armor/burned ...); NO per-zombie material (V2).',
    default: 4,
    min: 1,
    max: 16,
    integer: true,
  }),

  // ---- Per-instance variation modules (T30): composed, never a unique shader/material (V2) ----
  crowdBodyVariantCount: num({
    owner: 'rendering',
    unit: 'count',
    doc: 'Body mesh-module variants packed in the shared crowd atlas (variation, not new materials).',
    default: 6,
    min: 1,
    max: 64,
    integer: true,
  }),
  crowdHeadVariantCount: num({
    owner: 'rendering',
    unit: 'count',
    doc: 'Head module variants in the shared atlas.',
    default: 8,
    min: 1,
    max: 64,
    integer: true,
  }),
  crowdHairVariantCount: num({
    owner: 'rendering',
    unit: 'count',
    doc: 'Hair module variants in the shared atlas.',
    default: 6,
    min: 1,
    max: 64,
    integer: true,
  }),
  crowdClothingVariantCount: num({
    owner: 'rendering',
    unit: 'count',
    doc: 'Clothing module variants in the shared atlas.',
    default: 10,
    min: 1,
    max: 64,
    integer: true,
  }),
  crowdPaletteCount: num({
    owner: 'rendering',
    unit: 'count',
    doc: 'Palette/mask swatches for tinting variation (dirt/blood layered separately).',
    default: 12,
    min: 1,
    max: 256,
    integer: true,
  }),

  // ---- Block-limbed crowd (T72 / V2 / V13 / V17): hero + active-crowd zombies read as FIGURES so
  // dismemberment is VISIBLE. Composed from 6 shared per-part InstancedMeshes (NO per-zombie mesh, V2),
  // pooled to a budget. Per-part box dims live in CROWD_LIMB_PARTS below (art-direction proportions). ----
  crowdLimbedBudget: num({
    owner: 'rendering',
    unit: 'count',
    doc: 'Max simultaneously limbed (figure) zombies — the hero+active-crowd pool cap; extra figures fall through (T30 LOD).',
    default: 64,
    min: 0,
    max: 512,
    integer: true,
    tiers: { 'desktop-high': 128, 'desktop-medium': 64, 'desktop-compat': 32, 'mobile-webgpu': 16 },
  }),
  crowdLimbedMaxSimTier: num({
    owner: 'rendering',
    unit: 'count',
    doc: 'SoA simTier <= this is rendered as a limbed figure (0 hero, 1 active); higher tiers stay the instanced box (V13).',
    default: 1,
    min: 0,
    max: 3,
    integer: true,
  }),
  crowdLimbWalkSwingRadians: num({
    owner: 'rendering',
    unit: 'radians',
    doc: 'Peak arm/leg swing about local X driven by the SoA walk phase on limbed figures (idle/walk read).',
    default: 0.45,
    min: 0,
    max: 1.5,
  }),
  crowdLimbBobMeters: num({
    owner: 'rendering',
    unit: 'meters',
    doc: 'Peak vertical body bob applied to every part of a limbed figure from its SoA walk phase.',
    default: 0.05,
    min: 0,
    max: 0.5,
  }),

  // ---- Gore render (T19 / V8 / V29): pooled + capped; intensity multiplier injected from accessibility ----
  goreSprayPoolSize: num({
    owner: 'rendering',
    unit: 'count',
    doc: 'Fixed pool capacity for directional blood spray/mist emitters (recycled oldest-first when full).',
    default: 64,
    min: 0,
    max: 1024,
    integer: true,
    tiers: { 'desktop-high': 128, 'desktop-medium': 64, 'desktop-compat': 32, 'mobile-webgpu': 16 },
  }),
  goreStainPoolSize: num({
    owner: 'rendering',
    unit: 'count',
    doc: 'Fixed pool capacity for persistent readable blood stains/decals.',
    default: 256,
    min: 0,
    max: 4096,
    integer: true,
    tiers: { 'desktop-high': 512, 'desktop-medium': 256, 'desktop-compat': 128, 'mobile-webgpu': 48 },
  }),
  goreSeverPoolSize: num({
    owner: 'rendering',
    unit: 'count',
    doc: 'Fixed pool capacity for sever-silhouette / wound-cap gore markers.',
    default: 48,
    min: 0,
    max: 512,
    integer: true,
    tiers: { 'desktop-high': 96, 'desktop-medium': 48, 'desktop-compat': 24, 'mobile-webgpu': 8 },
  }),
  goreSprayParticlesPerEvent: num({
    owner: 'rendering',
    unit: 'count',
    doc: 'Particles emitted per hero blood-spray event at full gore intensity (scaled by accessibility + distance).',
    default: 12,
    min: 1,
    max: 200,
    integer: true,
    tiers: { 'desktop-high': 20, 'desktop-compat': 8, 'mobile-webgpu': 4 },
  }),
  goreDistantSimplifyMeters: num({
    owner: 'rendering',
    unit: 'meters',
    doc: 'Beyond this distance gore uses the pooled simplified form (no hero wet response).',
    default: 20,
    min: 1,
    max: 200,
  }),

  // ---- Combat feedback (B7 — muzzle flash / tracer / impact spark fed by VisualEvent + fire) ----
  combatSparkLifetimeSeconds: num({
    owner: 'rendering',
    unit: 'seconds',
    doc: 'Lifetime of a pooled impact-spark/blood marker spawned from a hit VisualEvent before it is recycled (B7).',
    default: 0.4,
    min: 0.05,
    max: 5,
  }),
  combatMuzzleFlashSeconds: num({
    owner: 'rendering',
    unit: 'seconds',
    doc: 'Duration of the muzzle-flash light + sprite pulse on player fire (B7).',
    default: 0.06,
    min: 0.01,
    max: 1,
  }),
  combatTracerSeconds: num({
    owner: 'rendering',
    unit: 'seconds',
    doc: 'Duration the shot tracer segment stays visible after firing (B7).',
    default: 0.08,
    min: 0.01,
    max: 1,
  }),
  combatMuzzleFlashIntensity: num({
    owner: 'rendering',
    unit: 'ratio',
    doc: 'Peak intensity of the muzzle-flash point light at full feedback before accessibility flash reduction (B7).',
    default: 6,
    min: 0,
    max: 50,
  }),
  combatTracerRangeMeters: num({
    owner: 'rendering',
    unit: 'meters',
    doc: 'Max length of the rendered shot tracer (the clean-miss length; a hit terminates at the struck-body travel — B15/V49).',
    default: 30,
    min: 1,
    max: 400,
  }),
  combatMuzzleOffsetMeters: num({
    owner: 'rendering',
    unit: 'meters',
    doc: 'Forward offset along the aim vector from the player body CENTRE to the weapon muzzle. The muzzle flash / tracer / impact ORIGINATE at playerPos + aim*offset (in front of the player), never at the body centre/back (B20-muzzle/V55, T78). Just beyond the body capsule radius so the beam exits in front of the avatar.',
    default: 0.7,
    min: 0,
    max: 3,
  }),

  // ---- Gore overhaul (B14/T71/V48): directional velocity spray from the struck region height + ground splat ----
  // No magic numbers — the region->height map, particle ballistics, splat size + lifetime are all typed here.
  combatGoreSprayParticleSizeMeters: num({
    owner: 'rendering',
    unit: 'meters',
    doc: 'Base edge length of ONE billboarded blood droplet quad. Energy only nudges it within sane bounds — never a meters-scale square (V48/B14).',
    default: 0.07,
    min: 0.01,
    max: 0.5,
    tiers: { 'desktop-high': 0.08, 'desktop-compat': 0.06, 'mobile-webgpu': 0.05 },
  }),
  combatGoreSprayVelocityMps: num({
    owner: 'rendering',
    unit: 'metersPerSecond',
    doc: 'Initial droplet speed launched ALONG the impact vector (hitReaction dirX/dirZ) before the gravity settle (V48).',
    default: 5,
    min: 0,
    max: 40,
  }),
  combatGoreSprayUpwardMps: num({
    owner: 'rendering',
    unit: 'metersPerSecond',
    doc: 'Initial upward component giving the spray its arc before gravity pulls droplets back down (V48).',
    default: 2.5,
    min: 0,
    max: 40,
  }),
  combatGoreSpraySpreadMps: num({
    owner: 'rendering',
    unit: 'metersPerSecond',
    doc: 'Peak lateral (perpendicular-to-impact) velocity spread per droplet — the fan of the spray (V48).',
    default: 2,
    min: 0,
    max: 40,
  }),
  combatGoreSprayGravityMps2: num({
    owner: 'rendering',
    unit: 'ratio',
    doc: 'Downward acceleration (m/s^2) applied over a droplet lifetime so the spray settles toward the ground (V48).',
    default: 9.81,
    min: 0,
    max: 40,
  }),
  combatGoreStainSizeMeters: num({
    owner: 'rendering',
    unit: 'meters',
    doc: 'Edge length of the persistent flattened ground-splat decal at the projected impact point (V48).',
    default: 0.45,
    min: 0.05,
    max: 5,
    tiers: { 'desktop-high': 0.55, 'mobile-webgpu': 0.35 },
  }),
  combatGoreStainLifetimeSeconds: num({
    owner: 'rendering',
    unit: 'seconds',
    doc: 'How long a ground splat stays before fading out — readable persistent stain, far longer than the airborne spark lifetime (V48).',
    default: 9,
    min: 0.5,
    max: 120,
    tiers: { 'desktop-high': 12, 'mobile-webgpu': 5 },
  }),
  combatGoreHeightHeadMeters: num({
    owner: 'rendering',
    unit: 'meters',
    doc: 'World height above the body base at which head/neck hits emit blood (region->height map, V48).',
    default: 1.7,
    min: 0,
    max: 5,
  }),
  combatGoreHeightTorsoMeters: num({
    owner: 'rendering',
    unit: 'meters',
    doc: 'World height above the body base for torso/arm hits — the mid band (region->height map, V48).',
    default: 1.1,
    min: 0,
    max: 5,
  }),
  combatGoreHeightLegMeters: num({
    owner: 'rendering',
    unit: 'meters',
    doc: 'World height above the body base for leg hits — the low band (region->height map, V48).',
    default: 0.4,
    min: 0,
    max: 5,
  }),

  // ---- Visibility / cutaway (T28 / V20): roof+upper-wall fade, base preserved, interiors stay hidden ----
  roofFadeSeconds: num({
    owner: 'rendering',
    unit: 'seconds',
    doc: 'Time to fade a roof/upper-wall section in or out as occlusion state changes (V20).',
    default: 0.25,
    min: 0,
    max: 5,
  }),
  wallPanelThicknessMeters: num({
    owner: 'rendering',
    unit: 'meters',
    doc: 'Thickness of a wall-shell panel (≪ navCell). Walls are thin oriented shells on exposed cell edges, not cell-filling blocks (B3).',
    default: 0.25,
    min: 0.02,
    max: 2,
  }),
  wallBasePreservedHeightMeters: num({
    owner: 'rendering',
    unit: 'meters',
    doc: 'Wall height (from floor up) always kept opaque to read enclosure + breach state (V20).',
    default: 1.2,
    min: 0.1,
    max: 10,
  }),
  cutawayCameraFacingDotThreshold: num({
    owner: 'rendering',
    unit: 'ratio',
    doc: 'DIRECTIONAL cutaway (T82/V58): an upper wall fades only when its outward normal turns toward the camera — dot(outwardNormal, towardCamera) > this threshold. Walls facing away (the FAR walls) stay opaque so enclosure still reads, so the room is never reduced to a roofless open box. Cosine in [-1,1]; ~0.2 fades the near walls between camera + player while keeping the far + grazing walls (V58).',
    default: 0.2,
    min: -1,
    max: 1,
  }),

  // ---- Pooled BLOOD system (T75 / V51): directional droplets that arc under gravity+drag and LAND as
  // drying directional floor decals; bloody footsteps while the player is freshly blood-soaked. Supersedes
  // the basic combat-feedback blood spray. Pooled + hard-capped, no per-frame alloc (V24). No magic numbers.
  bloodDropletPoolSize: num({
    owner: 'rendering',
    unit: 'count',
    doc: 'Hard cap on airborne blood droplets (T75/V51). Swap-removed on landing; spawn breaks at the cap (V24).',
    default: 1024,
    min: 16,
    max: 8192,
    integer: true,
    tiers: { 'desktop-high': 1536, 'desktop-compat': 640, 'mobile-webgpu': 384 },
  }),
  bloodDecalPoolSize: num({
    owner: 'rendering',
    unit: 'count',
    doc: 'Hard cap on settled blood floor decals (T75/V51). Ring buffer — oldest recycled past the cap (V24).',
    default: 256,
    min: 8,
    max: 2048,
    integer: true,
    tiers: { 'desktop-high': 384, 'desktop-compat': 160, 'mobile-webgpu': 96 },
  }),
  bloodGravityMps2: num({
    owner: 'rendering',
    unit: 'metersPerSecond',
    doc: 'Downward acceleration applied to airborne blood droplets so they arc and land (T75/V51).',
    default: 22,
    min: 1,
    max: 60,
  }),
  bloodAirDragPerSecond: num({
    owner: 'rendering',
    unit: 'ratio',
    doc: 'Horizontal speed shed per second by airborne droplets so blood lands near the kill, not across the map (T75/V51).',
    default: 9,
    min: 0,
    max: 30,
  }),
  bloodFloorYMeters: num({
    owner: 'rendering',
    unit: 'meters',
    doc: 'Height at which a falling droplet is considered landed and at which decals rest above the floor (T75/V51).',
    default: 0.04,
    min: 0,
    max: 1,
  }),
  bloodDecalLifeSeconds: num({
    owner: 'rendering',
    unit: 'seconds',
    doc: 'Total visible life of a settled blood decal: held fresh briefly, darkened to the dried-blood colour, then it LINGERS dried for the long remainder before a gentle end-of-life fade and ring-buffer recycle (T75/V51, lengthened T77/V54 — slow decay + long dried phase, capped by the decal pool).',
    default: 75,
    min: 0.5,
    max: 240,
    tiers: { 'desktop-high': 90, 'mobile-webgpu': 45 },
  }),
  bloodDecalFreshSeconds: num({
    owner: 'rendering',
    unit: 'seconds',
    doc: 'How long a settled decal holds its fresh (wet) colour before it starts darkening toward the dried-blood colour (T77/V54).',
    default: 4,
    min: 0,
    max: 60,
  }),
  bloodDecalDryTransitionSeconds: num({
    owner: 'rendering',
    unit: 'seconds',
    doc: 'Duration over which a settled decal darkens from its fresh colour to the dried-blood colour, after the fresh hold (T77/V54).',
    default: 9,
    min: 0.1,
    max: 120,
  }),
  bloodDecalFadeFraction: num({
    owner: 'rendering',
    unit: 'ratio',
    doc: 'Final fraction of a decal lifetime spent gently fading the dried stain into the floor shadow before the ring buffer recycles it — avoids an abrupt pop (T77/V54).',
    default: 0.15,
    min: 0.01,
    max: 1,
  }),
  bloodDecalStainChance: num({
    owner: 'rendering',
    unit: 'ratio',
    doc: 'Base probability (scaled by droplet size) that a landing droplet leaves a floor stain rather than evaporating. Raised for JUICE (T79) so most visible sprays paint the floor — combined with a GUARANTEED >=1 stain per hit, blood never appears to fall THROUGH the floor. Still capped + pooled by the decal ring buffer.',
    default: 0.8,
    min: 0,
    max: 1,
  }),
  bloodWallSplatReachMeters: num({
    owner: 'rendering',
    unit: 'meters',
    doc: 'Max distance along the impact/spray direction at which a wall (or obstacle) behind a struck body catches a vertical blood splat via the render-side surface raycast (T77/V54). 0 disables wall splats.',
    default: 3,
    min: 0,
    max: 20,
  }),
  bloodWallSplatCount: num({
    owner: 'rendering',
    unit: 'count',
    doc: 'Number of vertical decals stamped on a wall the spray ray strikes behind a struck body — a small lopsided cluster, not a single disc (T77/V54).',
    default: 3,
    min: 0,
    max: 24,
    integer: true,
    tiers: { 'desktop-high': 4, 'mobile-webgpu': 2 },
  }),
  bloodDecalDimFactor: num({
    owner: 'rendering',
    unit: 'ratio',
    doc: 'Fraction the fresh spray colour is darkened to when it settles as a soaked-in floor decal (T75/V51).',
    default: 0.68,
    min: 0.1,
    max: 1,
  }),
  bloodDropletsPerHit: num({
    owner: 'rendering',
    unit: 'count',
    doc: 'Base airborne droplet count thrown per hit at full energy before the low-skewed gush, accessibility + distance scaling (T75/V51, tuned DOWN T77/V54 — most hits a modest spritz, only the occasional one erupts).',
    default: 6,
    min: 1,
    max: 64,
    integer: true,
    tiers: { 'desktop-high': 8, 'desktop-compat': 4, 'mobile-webgpu': 3 },
  }),
  bloodSeverExtraDroplets: num({
    owner: 'rendering',
    unit: 'count',
    doc: 'Extra blood droplets thrown at the last impact point when a part is detached (partDetached, T75/V51).',
    default: 16,
    min: 0,
    max: 96,
    integer: true,
    tiers: { 'desktop-high': 24, 'mobile-webgpu': 8 },
  }),
  bloodDropletSpeedMinMps: num({
    owner: 'rendering',
    unit: 'metersPerSecond',
    doc: 'Minimum initial droplet speed along the hit vector (T75/V51).',
    default: 4,
    min: 0,
    max: 40,
  }),
  bloodDropletSpeedMaxMps: num({
    owner: 'rendering',
    unit: 'metersPerSecond',
    doc: 'Maximum initial droplet speed along the hit vector (T75/V51).',
    default: 11,
    min: 0,
    max: 60,
  }),
  bloodDropletUpwardMps: num({
    owner: 'rendering',
    unit: 'metersPerSecond',
    doc: 'Initial upward velocity giving the spray its arc before gravity pulls droplets down (T75/V51).',
    default: 3.4,
    min: 0,
    max: 40,
  }),
  bloodSpreadRad: num({
    owner: 'rendering',
    unit: 'radians',
    doc: 'Cone half-spread of the droplet jet around the hit direction on a normal hit (T75/V51).',
    default: 0.9,
    min: 0,
    max: 3.15,
  }),
  bloodCritSpreadRad: num({
    owner: 'rendering',
    unit: 'radians',
    doc: 'Tighter cone half-spread for a headshot/crit so the jet reads as a hard directional spurt (T75/V51).',
    default: 0.32,
    min: 0,
    max: 3.15,
  }),
  bloodDropletSizeMeters: num({
    owner: 'rendering',
    unit: 'meters',
    doc: 'Base radius of a blood droplet sphere; per-droplet random + energy scale it (T75/V51).',
    default: 0.07,
    min: 0.01,
    max: 0.5,
    tiers: { 'desktop-high': 0.08, 'mobile-webgpu': 0.05 },
  }),
  bloodDistantSimplifyMeters: num({
    owner: 'rendering',
    unit: 'meters',
    doc: 'Beyond this camera distance the blood droplet count is reduced (V8 distance simplification, T75/V51).',
    default: 22,
    min: 1,
    max: 200,
  }),
  bloodDistantCountScale: num({
    owner: 'rendering',
    unit: 'ratio',
    doc: 'Multiplier applied to the droplet count beyond the distant-simplify distance (V8, T75/V51).',
    default: 0.35,
    min: 0.01,
    max: 1,
  }),
  bloodFootstepCadenceSeconds: num({
    owner: 'rendering',
    unit: 'seconds',
    doc: 'Minimum time between bloody-footprint decals while the player is blood-soaked and moving (T75/V51, lengthened T77/V54 — infrequent prints).',
    default: 0.6,
    min: 0.02,
    max: 5,
  }),
  bloodFootstepPrintSizeMeters: num({
    owner: 'rendering',
    unit: 'meters',
    doc: 'Base size of a bloody footprint decal at full coverage — small + subtle, NOT a blobby puddle (T77/V54).',
    default: 0.16,
    min: 0.02,
    max: 1,
  }),
  bloodFootstepStrideOffsetMeters: num({
    owner: 'rendering',
    unit: 'meters',
    doc: 'Lateral offset of a footprint from the player path (alternating left/right foot) (T75/V51).',
    default: 0.26,
    min: 0,
    max: 2,
  }),
  bloodFootstepRangeMeters: num({
    owner: 'rendering',
    unit: 'meters',
    doc: 'Blood spawned within this distance of the player adds to their tracked wetness for footprints (T75/V51).',
    default: 4.4,
    min: 0.1,
    max: 30,
  }),
  bloodFootstepWetnessGainPerHit: num({
    owner: 'rendering',
    unit: 'ratio',
    doc: 'Wetness gained when a blood event lands right on the player (scaled down by distance) (T75/V51). Raised for JUICE (T79) so fighting in a cluster soaks the player and footprints actually appear.',
    default: 0.5,
    min: 0,
    max: 10,
  }),
  bloodFootstepWetnessDecayPerSecond: num({
    owner: 'rendering',
    unit: 'ratio',
    doc: 'Wetness lost per second as tracked blood dries off the player (T75/V51).',
    default: 0.12,
    min: 0,
    max: 10,
  }),
  bloodFootstepWetnessThreshold: num({
    owner: 'rendering',
    unit: 'ratio',
    doc: 'Minimum tracked wetness before the player leaves bloody footprints (T75/V51). Lowered for JUICE (T79) so prints appear once the player is soaked from a close fight or after walking through a fresh puddle — previously the threshold was so high it never triggered.',
    default: 0.6,
    min: 0,
    max: 10,
  }),

  // ---- Blood JUICE upgrade (T79): airborne motion streaks, player-body gore coating, puddle-step pickup.
  // All pooled + hard-capped (V24), render-local RNG only (V2/V3), no per-frame alloc, no magic numbers (V4).
  bloodDropletStreakLengthFactor: num({
    owner: 'rendering',
    unit: 'ratio',
    doc: 'How much an airborne droplet stretches ALONG its velocity per m/s of speed: long-axis = size*(1 + speed*factor), cross-section stays = size. Makes fast droplets read as motion STREAKS, not balls (T79).',
    default: 0.12,
    min: 0,
    max: 2,
  }),
  bloodCoatRangeMeters: num({
    owner: 'rendering',
    unit: 'meters',
    doc: 'A blood spray within this distance of the player splatters gore onto the PLAYER BODY (the body-gore coating layer). Beyond it, only world decals are placed (T79).',
    default: 4.4,
    min: 0,
    max: 30,
  }),
  bloodPlayerGorePoolSize: num({
    owner: 'rendering',
    unit: 'count',
    doc: 'Hard cap on accumulated body-gore splats stuck on the player (T79). Ring buffer — oldest recycled past the cap (V24).',
    default: 96,
    min: 0,
    max: 1024,
    integer: true,
    tiers: { 'desktop-high': 128, 'desktop-compat': 64, 'mobile-webgpu': 48 },
  }),
  bloodPlayerGoreLifeSeconds: num({
    owner: 'rendering',
    unit: 'seconds',
    doc: 'How long a body-gore splat lingers on the player before it dries + shrinks away — set FAR longer than the floor decal WET phase (~13s) so a sustained fight leaves the player visibly drenched (≈10× the wet phase, T79).',
    default: 55,
    min: 1,
    max: 300,
    tiers: { 'desktop-high': 75, 'mobile-webgpu': 35 },
  }),
  bloodPlayerGoreSizeMeters: num({
    owner: 'rendering',
    unit: 'meters',
    doc: 'Base radius of one body-gore splat slapped onto the player (per-splat random scale on top); flattened against the body surface so it hugs, not pokes out (T79).',
    default: 0.13,
    min: 0.02,
    max: 1,
    tiers: { 'desktop-high': 0.15, 'mobile-webgpu': 0.11 },
  }),
  bloodPlayerGoreBrightness: num({
    owner: 'rendering',
    unit: 'ratio',
    doc: 'Brightness multiplier applied to body-gore splat colour so fresh coating reads on the dark body — brighter than the soaked-in floor decals (T79).',
    default: 1.35,
    min: 0.5,
    max: 3,
  }),
  bloodPlayerGoreBodyRadiusMeters: num({
    owner: 'rendering',
    unit: 'meters',
    doc: 'Radial distance from the player body centre at which body-gore splats sit (on the body surface) — a BODY-LOCAL offset added to the tracked player world position each frame (T79).',
    default: 0.5,
    min: 0.05,
    max: 3,
  }),
  bloodPlayerGoreBodyHeightMinMeters: num({
    owner: 'rendering',
    unit: 'meters',
    doc: 'Lowest body-local height a coating splat lands at, up the player body (T79).',
    default: 0.4,
    min: 0,
    max: 5,
  }),
  bloodPlayerGoreBodyHeightMaxMeters: num({
    owner: 'rendering',
    unit: 'meters',
    doc: 'Highest body-local height a coating splat lands at, up the player body (T79).',
    default: 2,
    min: 0,
    max: 5,
  }),
  bloodPlayerGoreSplatsPerCoat: num({
    owner: 'rendering',
    unit: 'count',
    doc: 'Max body-gore splats spawned by ONE point-blank spray (scaled down by distance + energy). Always >=1 within coat range. Pooled (V24) (T79).',
    default: 6,
    min: 1,
    max: 32,
    integer: true,
  }),
  bloodPuddlePickupRadiusMeters: num({
    owner: 'rendering',
    unit: 'meters',
    doc: 'Walking within this distance of a FRESH (still-wet) floor decal soaks the player → builds wetness → leaves a bloody footprint trail for a short while (T79). Own footprints are excluded so the trail naturally ends.',
    default: 0.6,
    min: 0.05,
    max: 5,
  }),
  bloodPuddlePickupWetnessPerSecond: num({
    owner: 'rendering',
    unit: 'ratio',
    doc: 'Wetness gained per second while standing/walking in a fresh floor puddle (T79). Decays via bloodFootstepWetnessDecayPerSecond once the player leaves the blood.',
    default: 1.6,
    min: 0,
    max: 20,
  }),

  // ---- Pooled GIB system (T76 / V52): flung faceted lit meat chunks that tumble, land, settle, then dry +
  // shrink away. Sibling to the blood spray but SOLID matter — lit MeshStandardMaterial, low emissive so dark
  // gore reads on the dark floor (B6). Driven by partDetached (sever) + strong hits. Pooled + capped (V24).
  gibPoolSize: num({
    owner: 'rendering',
    unit: 'count',
    doc: 'Hard cap on live gib meat chunks (T76/V52). Ring buffer — oldest recycled past the cap (V24).',
    default: 512,
    min: 8,
    max: 4096,
    integer: true,
    tiers: { 'desktop-high': 768, 'desktop-compat': 320, 'mobile-webgpu': 192 },
  }),
  gibGravityMps2: num({
    owner: 'rendering',
    unit: 'metersPerSecond',
    doc: 'Downward acceleration on airborne gib chunks — a touch heavier than blood so lumps drop hard (T76/V52).',
    default: 26,
    min: 1,
    max: 80,
  }),
  gibAirDragPerSecond: num({
    owner: 'rendering',
    unit: 'ratio',
    doc: 'Horizontal speed shed per second by airborne gib chunks (T76/V52).',
    default: 7,
    min: 0,
    max: 30,
  }),
  gibFloorYMeters: num({
    owner: 'rendering',
    unit: 'meters',
    doc: 'Rest-height reference at which a gib chunk lands and settles above the floor (T76/V52).',
    default: 0.05,
    min: 0,
    max: 1,
  }),
  gibSettleLifeSeconds: num({
    owner: 'rendering',
    unit: 'seconds',
    doc: 'How long a gib chunk lingers (airborne + grounded) before it dries away and recycles (T76/V52).',
    default: 7.5,
    min: 0.5,
    max: 120,
    tiers: { 'desktop-high': 10, 'mobile-webgpu': 5 },
  }),
  gibFadeFraction: num({
    owner: 'rendering',
    unit: 'ratio',
    doc: 'Final fraction of a gib chunk lifetime spent shrinking + dimming out (T76/V52).',
    default: 0.32,
    min: 0.01,
    max: 1,
  }),
  gibBaseSizeMeters: num({
    owner: 'rendering',
    unit: 'meters',
    doc: 'Base radius of the faceted gib chunk geometry; per-chunk random + energy scale it (T76/V52).',
    default: 0.26,
    min: 0.02,
    max: 2,
    tiers: { 'mobile-webgpu': 0.2 },
  }),
  gibSeverChunkCountMin: num({
    owner: 'rendering',
    unit: 'count',
    doc: 'Minimum chunks thrown when a part is detached (partDetached, T76/V52).',
    default: 3,
    min: 1,
    max: 32,
    integer: true,
  }),
  gibSeverChunkCountMax: num({
    owner: 'rendering',
    unit: 'count',
    doc: 'Maximum chunks thrown when a part is detached (partDetached, T76/V52).',
    default: 6,
    min: 1,
    max: 64,
    integer: true,
    tiers: { 'mobile-webgpu': 4 },
  }),
  gibSeverSpeedMinMps: num({
    owner: 'rendering',
    unit: 'metersPerSecond',
    doc: 'Minimum outward fling speed of a severed gib chunk (T76/V52).',
    default: 3,
    min: 0,
    max: 40,
  }),
  gibSeverSpeedMaxMps: num({
    owner: 'rendering',
    unit: 'metersPerSecond',
    doc: 'Maximum outward fling speed of a severed gib chunk (T76/V52).',
    default: 8,
    min: 0,
    max: 60,
  }),
  gibSeverUpwardMps: num({
    owner: 'rendering',
    unit: 'metersPerSecond',
    doc: 'Initial upward pop of a severed gib chunk before it arcs down (T76/V52).',
    default: 4.5,
    min: 0,
    max: 40,
  }),
  gibSpinMaxRadPerSec: num({
    owner: 'rendering',
    unit: 'radiansPerSecond',
    doc: 'Peak per-axis tumble rate of an airborne gib chunk (T76/V52).',
    default: 16,
    min: 0,
    max: 60,
  }),
  gibHitFleckEnergyThreshold: num({
    owner: 'rendering',
    unit: 'ratio',
    doc: 'Hit energy (0..1) above which a strong hit also flings a few small gib flecks (hit-driven gibs, T76/V52).',
    default: 0.75,
    min: 0,
    max: 1,
  }),
  gibHitFleckCount: num({
    owner: 'rendering',
    unit: 'count',
    doc: 'Number of small gib flecks flung by a hit above the fleck energy threshold (T76/V52).',
    default: 2,
    min: 0,
    max: 16,
    integer: true,
    tiers: { 'mobile-webgpu': 1 },
  }),
  gibEmissiveIntensity: num({
    owner: 'rendering',
    unit: 'ratio',
    doc: 'Low emissive intensity of the gib material so dark gore reads on the dark floor without glowing (B6, T76/V52).',
    default: 0.6,
    min: 0,
    max: 4,
  }),
  gibDistantSimplifyMeters: num({
    owner: 'rendering',
    unit: 'meters',
    doc: 'Beyond this camera distance the gib chunk count is reduced (V8 distance simplification, T76/V52).',
    default: 26,
    min: 1,
    max: 200,
  }),
  gibDistantCountScale: num({
    owner: 'rendering',
    unit: 'ratio',
    doc: 'Multiplier applied to the gib chunk count beyond the distant-simplify distance (V8, T76/V52).',
    default: 0.4,
    min: 0.01,
    max: 1,
  }),
  upperWallFadeStartHeightMeters: num({
    owner: 'rendering',
    unit: 'meters',
    doc: 'Wall height above which sections may fade when they occlude the camera view (V20).',
    default: 1.8,
    min: 0.2,
    max: 20,
  }),

  // ---- Surface-impact response (T80/T81 / V57): a DISTINCT, clearly NON-RED response to shooting a
  // WALL / structure (a clean miss that stops on structure) so a miss never reads like "blood beyond
  // range". A bright spark burst thrown OUT of the surface (opposite the bullet's travel) + a small
  // persistent dark bullet-HOLE decal on the struck surface; plus dark WOUND marks on struck bodies
  // (zombie + player). Blood is unchanged: it fires only on a real damage-hit (bloodView). Pooled +
  // hard-capped (V24), render-local RNG (V2/V3), decals follow the V56 depth policy (depthTest ON,
  // depthWrite OFF, polygon-offset; never depthTest:false). No magic numbers (V4).
  impactSparkPoolSize: num({
    owner: 'rendering',
    unit: 'count',
    doc: 'Hard cap on live impact-spark particles (T80/V57). Compacted swap-removed on expiry; spawn breaks at the cap (V24).',
    default: 256,
    min: 8,
    max: 4096,
    integer: true,
    tiers: { 'desktop-high': 384, 'desktop-compat': 128, 'mobile-webgpu': 64 },
  }),
  impactSparkCount: num({
    owner: 'rendering',
    unit: 'count',
    doc: 'Sparks thrown per structure impact at full feedback before reduce-flashes thinning (T80/V57).',
    default: 14,
    min: 1,
    max: 128,
    integer: true,
    tiers: { 'desktop-high': 20, 'desktop-compat': 8, 'mobile-webgpu': 6 },
  }),
  impactSparkSizeMeters: num({
    owner: 'rendering',
    unit: 'meters',
    doc: 'Base radius of one impact-spark particle; per-spark random scales it down (T80/V57).',
    default: 0.045,
    min: 0.005,
    max: 0.5,
    tiers: { 'desktop-high': 0.05, 'mobile-webgpu': 0.035 },
  }),
  impactSparkLifeSeconds: num({
    owner: 'rendering',
    unit: 'seconds',
    doc: 'Lifetime of an impact spark before it fades out and is recycled — short-lived flash (T80/V57).',
    default: 0.35,
    min: 0.05,
    max: 3,
  }),
  impactSparkSpeedMinMps: num({
    owner: 'rendering',
    unit: 'metersPerSecond',
    doc: 'Minimum launch speed of an impact spark out of the struck surface (T80/V57).',
    default: 4,
    min: 0,
    max: 60,
  }),
  impactSparkSpeedMaxMps: num({
    owner: 'rendering',
    unit: 'metersPerSecond',
    doc: 'Maximum launch speed of an impact spark out of the struck surface (T80/V57).',
    default: 11,
    min: 0,
    max: 80,
  }),
  impactSparkSpreadRad: num({
    owner: 'rendering',
    unit: 'radians',
    doc: 'Cone half-angle around the surface normal within which sparks are scattered (T80/V57).',
    default: 1.0,
    min: 0,
    max: 1.57,
  }),
  impactSparkGravityMps2: num({
    owner: 'rendering',
    unit: 'metersPerSecond',
    doc: 'Downward acceleration on airborne impact sparks so the burst arcs and falls (T80/V57).',
    default: 14,
    min: 0,
    max: 60,
  }),
  impactSparkDragPerSecond: num({
    owner: 'rendering',
    unit: 'ratio',
    doc: 'Speed shed per second by airborne sparks so the burst decelerates (T80/V57).',
    default: 6,
    min: 0,
    max: 30,
  }),
  impactSparkColorR: num({
    owner: 'rendering',
    unit: 'ratio',
    doc: 'Red channel of the bright impact-spark colour — a hot yellow-white, deliberately NON-RED so a wall hit never reads as blood (T80/V57).',
    default: 1,
    min: 0,
    max: 1,
  }),
  impactSparkColorG: num({
    owner: 'rendering',
    unit: 'ratio',
    doc: 'Green channel of the bright impact-spark colour (yellow-white, NON-RED) (T80/V57).',
    default: 0.82,
    min: 0,
    max: 1,
  }),
  impactSparkColorB: num({
    owner: 'rendering',
    unit: 'ratio',
    doc: 'Blue channel of the bright impact-spark colour (yellow-white, NON-RED) (T80/V57).',
    default: 0.4,
    min: 0,
    max: 1,
  }),
  impactHolePoolSize: num({
    owner: 'rendering',
    unit: 'count',
    doc: 'Hard cap on persistent bullet-hole decals on structures (T80/V57). Ring buffer — oldest recycled past the cap (V24).',
    default: 192,
    min: 8,
    max: 2048,
    integer: true,
    tiers: { 'desktop-high': 288, 'desktop-compat': 96, 'mobile-webgpu': 48 },
  }),
  impactHoleSizeMeters: num({
    owner: 'rendering',
    unit: 'meters',
    doc: 'Diameter of a bullet-hole decal disc projected on the struck surface (T80/V57).',
    default: 0.13,
    min: 0.02,
    max: 1,
    tiers: { 'desktop-high': 0.15, 'mobile-webgpu': 0.11 },
  }),
  impactHoleLifeSeconds: num({
    owner: 'rendering',
    unit: 'seconds',
    doc: 'How long a bullet hole persists before a gentle end-of-life fade and ring-buffer recycle — long-lived, far longer than a spark (T80/V57).',
    default: 60,
    min: 1,
    max: 240,
    tiers: { 'desktop-high': 90, 'mobile-webgpu': 35 },
  }),
  impactHoleFadeFraction: num({
    owner: 'rendering',
    unit: 'ratio',
    doc: 'Final fraction of a bullet-hole lifetime spent shrinking/fading out before the ring buffer recycles it (T80/V57).',
    default: 0.15,
    min: 0.01,
    max: 1,
  }),
  impactWoundPoolSize: num({
    owner: 'rendering',
    unit: 'count',
    doc: 'Hard cap on accumulated wound decals on bodies (zombie + player) (T81/V57). Ring buffer — oldest recycled past the cap (V24).',
    default: 160,
    min: 8,
    max: 2048,
    integer: true,
    tiers: { 'desktop-high': 240, 'desktop-compat': 80, 'mobile-webgpu': 48 },
  }),
  impactWoundSizeMeters: num({
    owner: 'rendering',
    unit: 'meters',
    doc: 'Diameter of a dark wound mark stamped at the struck region of a body (T81/V57).',
    default: 0.16,
    min: 0.02,
    max: 1,
    tiers: { 'desktop-high': 0.18, 'mobile-webgpu': 0.13 },
  }),
  impactWoundLifeSeconds: num({
    owner: 'rendering',
    unit: 'seconds',
    doc: 'How long a wound mark lingers on a body before fading out and recycling (T81/V57).',
    default: 45,
    min: 1,
    max: 240,
    tiers: { 'desktop-high': 60, 'mobile-webgpu': 30 },
  }),
  impactWoundFadeFraction: num({
    owner: 'rendering',
    unit: 'ratio',
    doc: 'Final fraction of a wound-mark lifetime spent fading out before the ring buffer recycles it (T81/V57).',
    default: 0.25,
    min: 0.01,
    max: 1,
  }),

  // ---- FireView (RENDER lane): additive billboard FLAMES + pooled flickering point LIGHTS + faint SMOKE
  // at burning cells. Pure visual mirror of the sim's burning-cell set (V2/V3). Pooled + capped (V24),
  // distance-simplified (V8), light count capped (V8/V22), flicker damped on reduce-flashes (V29). No
  // magic numbers in fireView.ts (V4) — every flame/light/smoke tunable lives here. ----
  fireMaxCells: num({
    owner: 'rendering', unit: 'count',
    doc: 'Maximum simultaneously-tracked burning cells the FireView draws flames/lights for (pool cap, V24).',
    default: 24, min: 1, max: 256, integer: true,
    tiers: { 'desktop-high': 48, 'desktop-medium': 32, 'desktop-compat': 24, 'mobile-webgpu': 12 },
  }),
  fireQuadsPerCell: num({
    owner: 'rendering', unit: 'count',
    doc: 'Stacked/jittered additive billboard quads per burning cell at full intensity (volume).',
    default: 4, min: 1, max: 12, integer: true,
    tiers: { 'desktop-high': 6, 'desktop-medium': 4, 'desktop-compat': 3, 'mobile-webgpu': 2 },
  }),
  fireQuadCapacity: num({
    owner: 'rendering', unit: 'count',
    doc: 'Hard cap on total flame quad instances across all fires (instanced-mesh capacity, V24).',
    default: 256, min: 4, max: 4096, integer: true,
    tiers: { 'desktop-high': 512, 'desktop-medium': 256, 'desktop-compat': 128, 'mobile-webgpu': 64 },
  }),
  fireBaseSizeMeters: num({
    owner: 'rendering', unit: 'meters',
    doc: 'Base width/height (m) of a flame billboard quad at full intensity.',
    default: 0.9, min: 0.05, max: 8,
    tiers: { 'desktop-high': 1, 'mobile-webgpu': 0.8 },
  }),
  fireSizeJitter: num({
    owner: 'rendering', unit: 'ratio',
    doc: 'Per-quad random size variance (0 = uniform, 0.4 = +/-40%) so the flame body is not a uniform card.',
    default: 0.4, min: 0, max: 1,
  }),
  fireQuadRiseMeters: num({
    owner: 'rendering', unit: 'meters',
    doc: 'Vertical offset (m) added per stacked quad index — builds the flame column upward.',
    default: 0.45, min: 0, max: 4,
  }),
  fireQuadJitterMeters: num({
    owner: 'rendering', unit: 'meters',
    doc: 'Horizontal random jitter (m) of stacked quads around the cell centre so the column is not a flat sheet.',
    default: 0.25, min: 0, max: 4,
  }),
  fireBaseHeightMeters: num({
    owner: 'rendering', unit: 'meters',
    doc: 'Height (m) above the cell floor where the flame column base sits.',
    default: 0.4, min: 0, max: 8,
  }),
  fireBaseOpacity: num({
    owner: 'rendering', unit: 'ratio',
    doc: 'Base opacity of the additive flame material (additive, so this scales glow contribution).',
    default: 0.85, min: 0.01, max: 1,
  }),
  fireGrowthPerSec: num({
    owner: 'rendering', unit: 'ratio',
    doc: 'Per-second rate a freshly-ignited flame ramps its visual intensity (0..1) toward full (catch-in).',
    default: 1.5, min: 0.05, max: 20,
  }),
  fireFlickerHz: num({
    owner: 'rendering', unit: 'hz',
    doc: 'Flicker frequency (Hz) of the per-quad animated scale/opacity.',
    default: 7, min: 0.1, max: 60,
  }),
  fireFlickerAmount: num({
    owner: 'rendering', unit: 'ratio',
    doc: 'Flicker amplitude (0..1) on flame scale + brightness — the animated liveliness of the fire.',
    default: 0.35, min: 0, max: 1,
  }),
  fireReduceFlashesFlicker: num({
    owner: 'rendering', unit: 'ratio',
    doc: 'Multiplier applied to flame/light flicker amplitude when reduce-flashes is enabled (V29 damping).',
    default: 0.2, min: 0, max: 1,
  }),
  fireColorHotR: num({ owner: 'rendering', unit: 'ratio', doc: 'Deep-orange flame BASE colour (linear) R component.', default: 0.95, min: 0, max: 1 }),
  fireColorHotG: num({ owner: 'rendering', unit: 'ratio', doc: 'Deep-orange flame BASE colour (linear) G component.', default: 0.32, min: 0, max: 1 }),
  fireColorHotB: num({ owner: 'rendering', unit: 'ratio', doc: 'Deep-orange flame BASE colour (linear) B component.', default: 0.05, min: 0, max: 1 }),
  fireColorTipR: num({ owner: 'rendering', unit: 'ratio', doc: 'Yellow flame TIP colour (linear) R component.', default: 1, min: 0, max: 1 }),
  fireColorTipG: num({ owner: 'rendering', unit: 'ratio', doc: 'Yellow flame TIP colour (linear) G component.', default: 0.85, min: 0, max: 1 }),
  fireColorTipB: num({ owner: 'rendering', unit: 'ratio', doc: 'Yellow flame TIP colour (linear) B component.', default: 0.3, min: 0, max: 1 }),
  // distance-simplify (V8): full quad count within START; linearly down to one quad by END; culled past CULL.
  fireSimplifyStartMeters: num({
    owner: 'rendering', unit: 'meters',
    doc: 'Camera distance (m) within which a fire draws its full quad count; simplification begins beyond it (V8).',
    default: 18, min: 1, max: 500,
  }),
  fireSimplifyEndMeters: num({
    owner: 'rendering', unit: 'meters',
    doc: 'Camera distance (m) beyond which a fire is simplified to a single quad (V8).',
    default: 45, min: 2, max: 1000,
  }),
  fireCullDistanceMeters: num({
    owner: 'rendering', unit: 'meters',
    doc: 'Camera distance (m) beyond which a fire draws no flames and gets no light (V8 cull).',
    default: 70, min: 4, max: 2000,
  }),
  // pooled flickering point lights (V8/V22): only the N strongest nearby fires light the scene.
  fireLightCount: num({
    owner: 'rendering', unit: 'count',
    doc: 'Maximum simultaneous flickering point lights (only the N strongest nearby fires are lit, V8/V22).',
    default: 3, min: 0, max: 16, integer: true,
    tiers: { 'desktop-high': 4, 'desktop-medium': 3, 'desktop-compat': 2, 'mobile-webgpu': 1 },
  }),
  fireLightIntensity: num({
    owner: 'rendering', unit: 'ratio',
    doc: 'Base intensity of a fire point light at full burn intensity (scaled by intensity + flicker).',
    default: 6, min: 0, max: 200,
  }),
  fireLightRangeMeters: num({
    owner: 'rendering', unit: 'meters',
    doc: 'Distance (m) over which a fire point light falls off to zero.',
    default: 12, min: 0.5, max: 200,
  }),
  fireLightHeightMeters: num({
    owner: 'rendering', unit: 'meters',
    doc: 'Height (m) above the cell floor where a fire point light sits.',
    default: 1.2, min: 0, max: 12,
  }),
  fireLightFlickerAmount: num({
    owner: 'rendering', unit: 'ratio',
    doc: 'Flicker amplitude (0..1) on a fire point-light intensity (damped by reduce-flashes, V29).',
    default: 0.3, min: 0, max: 1,
  }),
  fireLightColorR: num({ owner: 'rendering', unit: 'ratio', doc: 'Warm fire point-light colour (linear) R component.', default: 1, min: 0, max: 1 }),
  fireLightColorG: num({ owner: 'rendering', unit: 'ratio', doc: 'Warm fire point-light colour (linear) G component.', default: 0.55, min: 0, max: 1 }),
  fireLightColorB: num({ owner: 'rendering', unit: 'ratio', doc: 'Warm fire point-light colour (linear) B component.', default: 0.2, min: 0, max: 1 }),
  // faint drifting smoke above strong fires (V56 depth policy). Skippable per tier via fireSmokeEnabled.
  fireSmokeEnabled: bool({
    owner: 'rendering',
    doc: 'Whether the FireView draws a faint drifting smoke billboard above strong fires (V56).',
    default: true,
    tiers: { 'mobile-webgpu': false },
  }),
  fireSmokeIntensityThreshold: num({
    owner: 'rendering', unit: 'ratio',
    doc: 'Minimum burn intensity (0..1) a fire needs before it grows a smoke billboard.',
    default: 0.6, min: 0, max: 1,
  }),
  fireSmokeSizeMeters: num({
    owner: 'rendering', unit: 'meters',
    doc: 'Width/height (m) of the faint smoke billboard above a strong fire.',
    default: 1.6, min: 0.1, max: 12,
  }),
  fireSmokeOpacity: num({
    owner: 'rendering', unit: 'ratio',
    doc: 'Opacity of the faint smoke billboard (kept low/tasteful so it never washes the scene out).',
    default: 0.18, min: 0, max: 1,
  }),
  fireSmokeRiseMeters: num({
    owner: 'rendering', unit: 'meters',
    doc: 'Height (m) above the cell floor where the smoke billboard centres + drifts upward.',
    default: 2, min: 0, max: 20,
  }),
  fireSmokeColorR: num({ owner: 'rendering', unit: 'ratio', doc: 'Dark smoke billboard colour (linear) R component.', default: 0.06, min: 0, max: 1 }),
  fireSmokeColorG: num({ owner: 'rendering', unit: 'ratio', doc: 'Dark smoke billboard colour (linear) G component.', default: 0.06, min: 0, max: 1 }),
  fireSmokeColorB: num({ owner: 'rendering', unit: 'ratio', doc: 'Dark smoke billboard colour (linear) B component.', default: 0.07, min: 0, max: 1 }),

  // ---- T87 residential house render dressing (clapboard/ivy/debris/porch/chimney sizing) ----
  // Geometric scales for the believable-house look; the per-house VARIATION/DISARRAY probabilities live in
  // the `world` domain, these are the render-side prop dimensions (V4).
  houseClapboardSpacingMeters: num({
    owner: 'rendering', unit: 'meters',
    doc: 'Vertical spacing between horizontal clapboard/lap-siding trim lines on house walls (T87).',
    default: 0.5, min: 0.15, max: 2,
  }),
  houseIvyPatchMeters: num({
    owner: 'rendering', unit: 'meters',
    doc: 'Edge size of one instanced ivy/overgrowth patch creeping a house wall (T87).',
    default: 0.7, min: 0.2, max: 3,
  }),
  houseDebrisMeters: num({
    owner: 'rendering', unit: 'meters',
    doc: 'Edge size of one instanced debris/rubble clump at a ruined house base (T87).',
    default: 0.55, min: 0.1, max: 3,
  }),
  housePorchHeightMeters: num({
    owner: 'rendering', unit: 'meters',
    doc: 'Height of a front-porch roof above its deck (post length) (T87).',
    default: 2.4, min: 1, max: 5,
  }),
  houseChimneyMeters: num({
    owner: 'rendering', unit: 'meters',
    doc: 'Plan edge size of a house chimney stack (T87).',
    default: 0.7, min: 0.2, max: 2,
  }),
});

// ---- Block-limbed figure layout (T72 / V2 / V13 / ART-DIRECTION) ----
// Stable, identity-mapped set of body parts composing a humanoid silhouette (~1.8 m tall, origin at the
// feet). Box dims + local offsets are art-direction proportions, not perf knobs, so they live as a typed
// constant here (centralized + named — no literals in render code, V4) rather than per-field tier specs.
// `region` ties a part to its SoA anatomyFlags sever bit so a severed limb HIDES (V17); a null region
// (torso) is never severable. `swingSign` drives the counter-swinging walk gait. Order is the part order.

/** Identity of a block-limb body part. Render-side only; maps to an AnatomyRegion for the sever-hide. */
export type CrowdLimbId = 'torso' | 'head' | 'armLeft' | 'armRight' | 'legLeft' | 'legRight';

export interface CrowdLimbPart {
  readonly id: CrowdLimbId;
  /** Box geometry size in meters [width, height, depth]. */
  readonly size: readonly [number, number, number];
  /** Local center offset from the feet origin (pre per-instance scale), meters [x, y, z]. */
  readonly offset: readonly [number, number, number];
  /** Walk-phase swing sign about local X (arms/legs counter-swing); 0 keeps the part rigid. */
  readonly swingSign: number;
}

export const CROWD_LIMB_PARTS: readonly CrowdLimbPart[] = [
  { id: 'legLeft', size: [0.18, 0.85, 0.2], offset: [-0.13, 0.42, 0], swingSign: 1 },
  { id: 'legRight', size: [0.18, 0.85, 0.2], offset: [0.13, 0.42, 0], swingSign: -1 },
  { id: 'torso', size: [0.5, 0.75, 0.32], offset: [0, 1.2, 0], swingSign: 0 },
  { id: 'head', size: [0.3, 0.32, 0.3], offset: [0, 1.72, 0], swingSign: 0 },
  { id: 'armLeft', size: [0.14, 0.62, 0.16], offset: [-0.34, 1.2, 0], swingSign: -1 },
  { id: 'armRight', size: [0.14, 0.62, 0.16], offset: [0.34, 1.2, 0], swingSign: 1 },
];
