// Config domain: rendering — blood sub-domain field definitions (split from rendering.ts; no behavior change).
// Plain spec objects (NOT a registered domain); spread into registerDomain('rendering', …) by ../rendering.ts.

import { num } from '../../spec';

export const bloodFields = {
  // ---- Gore render (T19 / V8 / V29): pooled + capped; intensity multiplier injected from accessibility ----
  goreSprayPoolSize: num({
    owner: 'rendering',
    unit: 'count',
    doc: 'Fixed pool capacity for directional blood spray/mist emitters (recycled oldest-first when full).',
    default: 64,
    min: 0,
    max: 1024,
    integer: true,
    tiers: { 'desktop-high': 128, 'desktop-medium': 64, 'desktop-compat': 32, 'mobile-webgpu': 16 },
  }),
  goreStainPoolSize: num({
    owner: 'rendering',
    unit: 'count',
    doc: 'Fixed pool capacity for persistent readable blood stains/decals.',
    default: 256,
    min: 0,
    max: 4096,
    integer: true,
    tiers: { 'desktop-high': 512, 'desktop-medium': 256, 'desktop-compat': 128, 'mobile-webgpu': 48 },
  }),
  goreSeverPoolSize: num({
    owner: 'rendering',
    unit: 'count',
    doc: 'Fixed pool capacity for sever-silhouette / wound-cap gore markers.',
    default: 48,
    min: 0,
    max: 512,
    integer: true,
    tiers: { 'desktop-high': 96, 'desktop-medium': 48, 'desktop-compat': 24, 'mobile-webgpu': 8 },
  }),
  goreSprayParticlesPerEvent: num({
    owner: 'rendering',
    unit: 'count',
    doc: 'Particles emitted per hero blood-spray event at full gore intensity (scaled by accessibility + distance).',
    default: 12,
    min: 1,
    max: 200,
    integer: true,
    tiers: { 'desktop-high': 20, 'desktop-compat': 8, 'mobile-webgpu': 4 },
  }),
  goreDistantSimplifyMeters: num({
    owner: 'rendering',
    unit: 'meters',
    doc: 'Beyond this distance gore uses the pooled simplified form (no hero wet response).',
    default: 20,
    min: 1,
    max: 200,
  }),
  // ---- Pooled BLOOD system (T75 / V51): directional droplets that arc under gravity+drag and LAND as
  // drying directional floor decals; bloody footsteps while the player is freshly blood-soaked. Supersedes
  // the basic combat-feedback blood spray. Pooled + hard-capped, no per-frame alloc (V24). No magic numbers.
  bloodDropletPoolSize: num({
    owner: 'rendering',
    unit: 'count',
    doc: 'Hard cap on airborne blood droplets (T75/V51). Swap-removed on landing; spawn breaks at the cap (V24).',
    default: 1024,
    min: 16,
    max: 8192,
    integer: true,
    tiers: { 'desktop-high': 1536, 'desktop-compat': 640, 'mobile-webgpu': 384 },
  }),
  bloodDecalPoolSize: num({
    owner: 'rendering',
    unit: 'count',
    doc: 'Hard cap on settled blood floor decals (T75/V51). Ring buffer — oldest recycled past the cap (V24).',
    default: 256,
    min: 8,
    max: 2048,
    integer: true,
    tiers: { 'desktop-high': 384, 'desktop-compat': 160, 'mobile-webgpu': 96 },
  }),
  bloodGravityMps2: num({
    owner: 'rendering',
    unit: 'metersPerSecond',
    doc: 'Downward acceleration applied to airborne blood droplets so they arc and land (T75/V51).',
    default: 22,
    min: 1,
    max: 60,
  }),
  bloodAirDragPerSecond: num({
    owner: 'rendering',
    unit: 'ratio',
    doc: 'Horizontal speed shed per second by airborne droplets so blood lands near the kill, not across the map (T75/V51).',
    default: 9,
    min: 0,
    max: 30,
  }),
  bloodFloorYMeters: num({
    owner: 'rendering',
    unit: 'meters',
    doc: 'Height at which a falling droplet is considered landed and at which decals rest above the floor (T75/V51).',
    default: 0.04,
    min: 0,
    max: 1,
  }),
  bloodDecalLifeSeconds: num({
    owner: 'rendering',
    unit: 'seconds',
    doc: 'Total visible life of a settled blood decal: held fresh briefly, darkened to the dried-blood colour, then it LINGERS dried for the long remainder before a gentle end-of-life fade and ring-buffer recycle (T75/V51, lengthened T77/V54 — slow decay + long dried phase, capped by the decal pool).',
    default: 75,
    min: 0.5,
    max: 240,
    tiers: { 'desktop-high': 90, 'mobile-webgpu': 45 },
  }),
  bloodDecalFreshSeconds: num({
    owner: 'rendering',
    unit: 'seconds',
    doc: 'How long a settled decal holds its fresh (wet) colour before it starts darkening toward the dried-blood colour (T77/V54).',
    default: 4,
    min: 0,
    max: 60,
  }),
  bloodDecalDryTransitionSeconds: num({
    owner: 'rendering',
    unit: 'seconds',
    doc: 'Duration over which a settled decal darkens from its fresh colour to the dried-blood colour, after the fresh hold (T77/V54).',
    default: 9,
    min: 0.1,
    max: 120,
  }),
  bloodDecalFadeFraction: num({
    owner: 'rendering',
    unit: 'ratio',
    doc: 'Final fraction of a decal lifetime spent gently fading the dried stain into the floor shadow before the ring buffer recycles it — avoids an abrupt pop (T77/V54).',
    default: 0.15,
    min: 0.01,
    max: 1,
  }),
  bloodDecalStainChance: num({
    owner: 'rendering',
    unit: 'ratio',
    doc: 'Base probability (scaled by droplet size) that a landing droplet leaves a floor stain rather than evaporating. Raised for JUICE (T79) so most visible sprays paint the floor — combined with a GUARANTEED >=1 stain per hit, blood never appears to fall THROUGH the floor. Still capped + pooled by the decal ring buffer.',
    default: 0.8,
    min: 0,
    max: 1,
  }),
  bloodWallSplatReachMeters: num({
    owner: 'rendering',
    unit: 'meters',
    doc: 'Max distance along the impact/spray direction at which a wall (or obstacle) behind a struck body catches a vertical blood splat via the render-side surface raycast (T77/V54). 0 disables wall splats.',
    default: 3,
    min: 0,
    max: 20,
  }),
  bloodWallSplatCount: num({
    owner: 'rendering',
    unit: 'count',
    doc: 'Number of vertical decals stamped on a wall the spray ray strikes behind a struck body — a small lopsided cluster, not a single disc (T77/V54).',
    default: 3,
    min: 0,
    max: 24,
    integer: true,
    tiers: { 'desktop-high': 4, 'mobile-webgpu': 2 },
  }),
  bloodDecalDimFactor: num({
    owner: 'rendering',
    unit: 'ratio',
    doc: 'Fraction the fresh spray colour is darkened to when it settles as a soaked-in floor decal (T75/V51).',
    default: 0.68,
    min: 0.1,
    max: 1,
  }),
  bloodDropletsPerHit: num({
    owner: 'rendering',
    unit: 'count',
    doc: 'Base airborne droplet count thrown per hit at full energy before the low-skewed gush, accessibility + distance scaling (T75/V51, tuned DOWN T77/V54 — most hits a modest spritz, only the occasional one erupts).',
    default: 6,
    min: 1,
    max: 64,
    integer: true,
    tiers: { 'desktop-high': 8, 'desktop-compat': 4, 'mobile-webgpu': 3 },
  }),
  bloodSeverExtraDroplets: num({
    owner: 'rendering',
    unit: 'count',
    doc: 'Extra blood droplets thrown at the last impact point when a part is detached (partDetached, T75/V51).',
    default: 16,
    min: 0,
    max: 96,
    integer: true,
    tiers: { 'desktop-high': 24, 'mobile-webgpu': 8 },
  }),
  bloodDropletSpeedMinMps: num({
    owner: 'rendering',
    unit: 'metersPerSecond',
    doc: 'Minimum initial droplet speed along the hit vector (T75/V51).',
    default: 4,
    min: 0,
    max: 40,
  }),
  bloodDropletSpeedMaxMps: num({
    owner: 'rendering',
    unit: 'metersPerSecond',
    doc: 'Maximum initial droplet speed along the hit vector (T75/V51).',
    default: 11,
    min: 0,
    max: 60,
  }),
  bloodDropletUpwardMps: num({
    owner: 'rendering',
    unit: 'metersPerSecond',
    doc: 'Initial upward velocity giving the spray its arc before gravity pulls droplets down (T75/V51).',
    default: 3.4,
    min: 0,
    max: 40,
  }),
  bloodSpreadRad: num({
    owner: 'rendering',
    unit: 'radians',
    doc: 'Cone half-spread of the droplet jet around the hit direction on a normal hit (T75/V51).',
    default: 0.9,
    min: 0,
    max: 3.15,
  }),
  bloodCritSpreadRad: num({
    owner: 'rendering',
    unit: 'radians',
    doc: 'Tighter cone half-spread for a headshot/crit so the jet reads as a hard directional spurt (T75/V51).',
    default: 0.32,
    min: 0,
    max: 3.15,
  }),
  bloodDropletSizeMeters: num({
    owner: 'rendering',
    unit: 'meters',
    doc: 'Base radius of a blood droplet sphere; per-droplet random + energy scale it (T75/V51).',
    default: 0.07,
    min: 0.01,
    max: 0.5,
    tiers: { 'desktop-high': 0.08, 'mobile-webgpu': 0.05 },
  }),
  bloodDistantSimplifyMeters: num({
    owner: 'rendering',
    unit: 'meters',
    doc: 'Beyond this camera distance the blood droplet count is reduced (V8 distance simplification, T75/V51).',
    default: 22,
    min: 1,
    max: 200,
  }),
  bloodDistantCountScale: num({
    owner: 'rendering',
    unit: 'ratio',
    doc: 'Multiplier applied to the droplet count beyond the distant-simplify distance (V8, T75/V51).',
    default: 0.35,
    min: 0.01,
    max: 1,
  }),
  bloodFootstepCadenceSeconds: num({
    owner: 'rendering',
    unit: 'seconds',
    doc: 'Minimum time between bloody-footprint decals while the player is blood-soaked and moving (T75/V51, lengthened T77/V54 — infrequent prints).',
    default: 0.6,
    min: 0.02,
    max: 5,
  }),
  bloodFootstepPrintSizeMeters: num({
    owner: 'rendering',
    unit: 'meters',
    doc: 'Base size of a bloody footprint decal at full coverage — small + subtle, NOT a blobby puddle (T77/V54).',
    default: 0.16,
    min: 0.02,
    max: 1,
  }),
  bloodFootstepStrideOffsetMeters: num({
    owner: 'rendering',
    unit: 'meters',
    doc: 'Lateral offset of a footprint from the player path (alternating left/right foot) (T75/V51).',
    default: 0.26,
    min: 0,
    max: 2,
  }),
  bloodFootstepRangeMeters: num({
    owner: 'rendering',
    unit: 'meters',
    doc: 'Blood spawned within this distance of the player adds to their tracked wetness for footprints (T75/V51).',
    default: 4.4,
    min: 0.1,
    max: 30,
  }),
  bloodFootstepWetnessGainPerHit: num({
    owner: 'rendering',
    unit: 'ratio',
    doc: 'Wetness gained when a blood event lands right on the player (scaled down by distance) (T75/V51). Raised for JUICE (T79) so fighting in a cluster soaks the player and footprints actually appear.',
    default: 0.5,
    min: 0,
    max: 10,
  }),
  bloodFootstepWetnessDecayPerSecond: num({
    owner: 'rendering',
    unit: 'ratio',
    doc: 'Wetness lost per second as tracked blood dries off the player (T75/V51).',
    default: 0.12,
    min: 0,
    max: 10,
  }),
  bloodFootstepWetnessThreshold: num({
    owner: 'rendering',
    unit: 'ratio',
    doc: 'Minimum tracked wetness before the player leaves bloody footprints (T75/V51). Lowered for JUICE (T79) so prints appear once the player is soaked from a close fight or after walking through a fresh puddle — previously the threshold was so high it never triggered.',
    default: 0.6,
    min: 0,
    max: 10,
  }),
  // ---- Blood JUICE upgrade (T79): airborne motion streaks, player-body gore coating, puddle-step pickup.
  // All pooled + hard-capped (V24), render-local RNG only (V2/V3), no per-frame alloc, no magic numbers (V4).
  bloodDropletStreakLengthFactor: num({
    owner: 'rendering',
    unit: 'ratio',
    doc: 'How much an airborne droplet stretches ALONG its velocity per m/s of speed: long-axis = size*(1 + speed*factor), cross-section stays = size. Makes fast droplets read as motion STREAKS, not balls (T79).',
    default: 0.12,
    min: 0,
    max: 2,
  }),
  bloodCoatRangeMeters: num({
    owner: 'rendering',
    unit: 'meters',
    doc: 'A blood spray within this distance of the player splatters gore onto the PLAYER BODY (the body-gore coating layer). Beyond it, only world decals are placed (T79). Point-blank only — must be right on top of the source to get coated.',
    default: 1.3,
    min: 0,
    max: 30,
  }),
  bloodPlayerGorePoolSize: num({
    owner: 'rendering',
    unit: 'count',
    doc: 'Hard cap on accumulated body-gore splats stuck on the player (T79; toned DOWN — was too many/frequent). Ring buffer — oldest recycled past the cap (V24).',
    default: 48,
    min: 0,
    max: 1024,
    integer: true,
    tiers: { 'desktop-high': 64, 'desktop-compat': 40, 'mobile-webgpu': 28 },
  }),
  bloodPlayerGoreLifeSeconds: num({
    owner: 'rendering',
    unit: 'seconds',
    doc: 'How long a body-gore splat lingers on the player before it dries + shrinks away — set FAR longer than the floor decal WET phase (~13s) so a sustained fight leaves the player visibly drenched (≈10× the wet phase, T79).',
    default: 55,
    min: 1,
    max: 300,
    tiers: { 'desktop-high': 75, 'mobile-webgpu': 35 },
  }),
  bloodPlayerGoreSizeMeters: num({
    owner: 'rendering',
    unit: 'meters',
    doc: 'Base radius of one body-gore splat slapped onto the player (per-splat random scale on top); flattened against the body surface so it hugs, not pokes out (T79; toned DOWN — was too large/uniform).',
    default: 0.08,
    min: 0.02,
    max: 1,
    tiers: { 'desktop-high': 0.09, 'mobile-webgpu': 0.06 },
  }),
  bloodPlayerGoreBrightness: num({
    owner: 'rendering',
    unit: 'ratio',
    doc: 'Brightness multiplier applied to body-gore splat colour so fresh coating reads on the dark body (T79; toned DOWN from 1.35 — was too bright).',
    default: 0.95,
    min: 0.5,
    max: 3,
  }),
  bloodPlayerGoreBodyRadiusMeters: num({
    owner: 'rendering',
    unit: 'meters',
    doc: 'Radial distance from the player body centre at which body-gore splats sit (on the body surface) — a BODY-LOCAL offset added to the tracked player world position each frame (T79).',
    default: 0.5,
    min: 0.05,
    max: 3,
  }),
  bloodPlayerGoreBodyHeightMinMeters: num({
    owner: 'rendering',
    unit: 'meters',
    doc: 'Lowest body-local height a coating splat lands at, up the player body (T79).',
    default: 0.4,
    min: 0,
    max: 5,
  }),
  bloodPlayerGoreBodyHeightMaxMeters: num({
    owner: 'rendering',
    unit: 'meters',
    doc: 'Highest body-local height a coating splat lands at, up the player body (T79).',
    default: 2,
    min: 0,
    max: 5,
  }),
  bloodPlayerGoreSplatsPerCoat: num({
    owner: 'rendering',
    unit: 'count',
    doc: 'Max body-gore splats spawned by ONE point-blank spray (scaled down by distance + energy). Always >=1 within coat range. Pooled (V24) (T79; toned DOWN from 6 — was too frequent/dense).',
    default: 2,
    min: 1,
    max: 32,
    integer: true,
  }),
  bloodPuddlePickupRadiusMeters: num({
    owner: 'rendering',
    unit: 'meters',
    doc: 'Walking within this distance of a FRESH (still-wet) floor decal soaks the player → builds wetness → leaves a bloody footprint trail for a short while (T79). Own footprints are excluded so the trail naturally ends.',
    default: 0.6,
    min: 0.05,
    max: 5,
  }),
  bloodPuddlePickupWetnessPerSecond: num({
    owner: 'rendering',
    unit: 'ratio',
    doc: 'Wetness gained per second while standing/walking in a fresh floor puddle (T79). Decays via bloodFootstepWetnessDecayPerSecond once the player leaves the blood.',
    default: 1.6,
    min: 0,
    max: 20,
  }),
  // ---- Bug A: blood coated onto a ZOMBIE body follows that body to the floor (corpse), mirroring the
  //      player body-gore layer. Anchored to the struck entity + re-projected to its current transform each
  //      frame via an injected body-anchor resolver (live zombie while alive, corpse once it topples). ----
  bloodZombieGorePoolSize: num({
    owner: 'rendering',
    unit: 'count',
    doc: 'Hard cap on body-gore splats stuck on ZOMBIE bodies/corpses (Bug A). Ring buffer — oldest recycled past the cap (V24). Larger than the player pool since many bodies can be coated.',
    default: 192,
    min: 0,
    max: 4096,
    integer: true,
    tiers: { 'desktop-high': 256, 'desktop-compat': 160, 'mobile-webgpu': 96 },
  }),
  bloodZombieGoreSplatsPerHit: num({
    owner: 'rendering',
    unit: 'count',
    doc: 'Max body-gore splats coated onto the STRUCK zombie body by ONE blood spray (scaled by energy/intensity). Always >=1. Pooled (V24) (Bug A).',
    default: 3,
    min: 1,
    max: 32,
    integer: true,
  }),
  bloodZombieGoreBodyRadiusMeters: num({
    owner: 'rendering',
    unit: 'meters',
    doc: 'Radial distance from a zombie body axis at which body-gore splats sit — sized to HUG the thin humanoid limbs (much smaller than the player body), so coating gore stays ON the mesh surface instead of floating on a fat cylinder (V48 surface-anchoring).',
    default: 0.16,
    min: 0.03,
    max: 1,
  }),
  bloodZombieGoreHeightJitterMeters: num({
    owner: 'rendering',
    unit: 'meters',
    doc: 'Vertical jitter band around the STRUCK region height at which zombie body-gore splats land (keeps them clustered on the hit region, not smeared over the whole body) (V48).',
    default: 0.14,
    min: 0,
    max: 1,
  }),
};
