// Config domain: rendering — gib sub-domain field definitions (split from rendering.ts; no behavior change).
// Plain spec objects (NOT a registered domain); spread into registerDomain('rendering', …) by ../rendering.ts.

import { num } from '../../spec';

export const gibFields = {
  // ---- Pooled GIB system (T76 / V52): flung faceted lit meat chunks that tumble, land, settle, then dry +
  // shrink away. Sibling to the blood spray but SOLID matter — lit MeshStandardMaterial, low emissive so dark
  // gore reads on the dark floor (B6). Driven by partDetached (sever) + strong hits. Pooled + capped (V24).
  gibPoolSize: num({
    owner: 'rendering',
    unit: 'count',
    doc: 'Hard cap on live gib meat chunks (T76/V52). Ring buffer — oldest recycled past the cap (V24).',
    default: 512,
    min: 8,
    max: 4096,
    integer: true,
    tiers: { 'desktop-high': 768, 'desktop-compat': 320, 'mobile-webgpu': 192 },
  }),
  gibGravityMps2: num({
    owner: 'rendering',
    unit: 'metersPerSecond',
    doc: 'Downward acceleration on airborne gib chunks — a touch heavier than blood so lumps drop hard (T76/V52).',
    default: 26,
    min: 1,
    max: 80,
  }),
  gibAirDragPerSecond: num({
    owner: 'rendering',
    unit: 'ratio',
    doc: 'Horizontal speed shed per second by airborne gib chunks (T76/V52).',
    default: 7,
    min: 0,
    max: 30,
  }),
  gibFloorYMeters: num({
    owner: 'rendering',
    unit: 'meters',
    doc: 'Rest-height reference at which a gib chunk lands and settles above the floor (T76/V52).',
    default: 0.05,
    min: 0,
    max: 1,
  }),
  gibSettleLifeSeconds: num({
    owner: 'rendering',
    unit: 'seconds',
    doc: 'How long a gib chunk lingers (airborne + grounded) before it dries away and recycles (T76/V52).',
    default: 7.5,
    min: 0.5,
    max: 120,
    tiers: { 'desktop-high': 10, 'mobile-webgpu': 5 },
  }),
  gibFadeFraction: num({
    owner: 'rendering',
    unit: 'ratio',
    doc: 'Final fraction of a gib chunk lifetime spent shrinking + dimming out (T76/V52).',
    default: 0.32,
    min: 0.01,
    max: 1,
  }),
  gibBaseSizeMeters: num({
    owner: 'rendering',
    unit: 'meters',
    doc: 'Base radius of the faceted gib chunk geometry; per-chunk random + energy scale it (T76/V52). Small — a single shot should fling tiny specks, not plump lumps.',
    default: 0.13,
    min: 0.02,
    max: 2,
    tiers: { 'mobile-webgpu': 0.11 },
  }),
  gibSeverChunkCountMin: num({
    owner: 'rendering',
    unit: 'count',
    doc: 'Minimum chunks thrown when a part is detached (partDetached, T76/V52).',
    default: 2,
    min: 1,
    max: 32,
    integer: true,
  }),
  gibSeverChunkCountMax: num({
    owner: 'rendering',
    unit: 'count',
    doc: 'Maximum chunks thrown when a part is detached (partDetached, T76/V52).',
    default: 3,
    min: 1,
    max: 64,
    integer: true,
    tiers: { 'mobile-webgpu': 2 },
  }),
  gibSeverSpeedMinMps: num({
    owner: 'rendering',
    unit: 'metersPerSecond',
    doc: 'Minimum outward fling speed of a severed gib chunk (T76/V52).',
    default: 3,
    min: 0,
    max: 40,
  }),
  gibSeverSpeedMaxMps: num({
    owner: 'rendering',
    unit: 'metersPerSecond',
    doc: 'Maximum outward fling speed of a severed gib chunk (T76/V52).',
    default: 8,
    min: 0,
    max: 60,
  }),
  gibSeverUpwardMps: num({
    owner: 'rendering',
    unit: 'metersPerSecond',
    doc: 'Initial upward pop of a severed gib chunk before it arcs down (T76/V52).',
    default: 4.5,
    min: 0,
    max: 40,
  }),
  gibSpinMaxRadPerSec: num({
    owner: 'rendering',
    unit: 'radiansPerSecond',
    doc: 'Peak per-axis tumble rate of an airborne gib chunk (T76/V52).',
    default: 16,
    min: 0,
    max: 60,
  }),
  gibHitFleckEnergyThreshold: num({
    owner: 'rendering',
    unit: 'ratio',
    doc: 'Hit energy (0..1) above which a strong hit also flings a few small gib flecks (hit-driven gibs, T76/V52).',
    default: 0.75,
    min: 0,
    max: 1,
  }),
  gibHitFleckCount: num({
    owner: 'rendering',
    unit: 'count',
    doc: 'Number of small gib flecks flung by a hit that rolls a fleck (T76/V52). Kept low — most hits just spray blood, not meat.',
    default: 1,
    min: 0,
    max: 16,
    integer: true,
    tiers: { 'mobile-webgpu': 1 },
  }),
  gibHitFleckChance: num({
    owner: 'rendering',
    unit: 'ratio',
    doc: 'Per-hit PROBABILITY a (non-severing) hit also flings small meat flecks. Low so an ordinary shot mostly sprays blood — meat chunks read as the exception, not every shot (hit energy saturates at 1, so a probability gate, not the energy threshold, controls frequency) (T76/V52).',
    default: 0.16,
    min: 0,
    max: 1,
  }),
  gibSeverLimbDropChance: num({
    owner: 'rendering',
    unit: 'ratio',
    doc: 'Probability a SEVERED limb physically DROPS as a flung limb chunk (lands on the ground + bleeds) instead of simply vanishing. A decent chance so dismemberment leaves a body part behind (T76/V52/V17).',
    default: 0.6,
    min: 0,
    max: 1,
  }),
  gibSeverLimbSizeMul: num({
    owner: 'rendering',
    unit: 'ratio',
    doc: 'Size multiplier (× base gib size) of the dropped LIMB chunk — bigger than a fleck so it reads as a limb, not a speck (T76/V52). Trimmed from 2.8: at the high end of the per-chunk random it produced ~1 m boulder-sized lumps; a limb should read as a chunk, not a torso.',
    default: 1.6,
    min: 1,
    max: 8,
  }),
  gibEmissiveIntensity: num({
    owner: 'rendering',
    unit: 'ratio',
    doc: 'Low emissive intensity of the gib material so dark gore reads on the dark floor without glowing (B6, T76/V52).',
    default: 0.6,
    min: 0,
    max: 4,
  }),
  gibDistantSimplifyMeters: num({
    owner: 'rendering',
    unit: 'meters',
    doc: 'Beyond this camera distance the gib chunk count is reduced (V8 distance simplification, T76/V52).',
    default: 26,
    min: 1,
    max: 200,
  }),
  gibDistantCountScale: num({
    owner: 'rendering',
    unit: 'ratio',
    doc: 'Multiplier applied to the gib chunk count beyond the distant-simplify distance (V8, T76/V52).',
    default: 0.4,
    min: 0.01,
    max: 1,
  }),
};
