// Config domain: rendering — impact sub-domain field definitions (split from rendering.ts; no behavior change).
// Plain spec objects (NOT a registered domain); spread into registerDomain('rendering', …) by ../rendering.ts.

import { num } from '../../spec';

export const impactFields = {
  // ---- Surface-impact response (T80/T81 / V57): a DISTINCT, clearly NON-RED response to shooting a
  // WALL / structure (a clean miss that stops on structure) so a miss never reads like "blood beyond
  // range". A bright spark burst thrown OUT of the surface (opposite the bullet's travel) + a small
  // persistent dark bullet-HOLE decal on the struck surface; plus dark WOUND marks on struck bodies
  // (zombie + player). Blood is unchanged: it fires only on a real damage-hit (bloodView). Pooled +
  // hard-capped (V24), render-local RNG (V2/V3), decals follow the V56 depth policy (depthTest ON,
  // depthWrite OFF, polygon-offset; never depthTest:false). No magic numbers (V4).
  impactSparkPoolSize: num({
    owner: 'rendering',
    unit: 'count',
    doc: 'Hard cap on live impact-spark particles (T80/V57). Compacted swap-removed on expiry; spawn breaks at the cap (V24).',
    default: 256,
    min: 8,
    max: 4096,
    integer: true,
    tiers: { 'desktop-high': 384, 'desktop-compat': 128, 'mobile-webgpu': 64 },
  }),
  impactSparkCount: num({
    owner: 'rendering',
    unit: 'count',
    doc: 'Sparks thrown per structure impact at full feedback before reduce-flashes thinning (T80/V57).',
    default: 14,
    min: 1,
    max: 128,
    integer: true,
    tiers: { 'desktop-high': 20, 'desktop-compat': 8, 'mobile-webgpu': 6 },
  }),
  impactSparkSizeMeters: num({
    owner: 'rendering',
    unit: 'meters',
    doc: 'Base radius of one impact-spark particle; per-spark random scales it down (T80/V57).',
    default: 0.045,
    min: 0.005,
    max: 0.5,
    tiers: { 'desktop-high': 0.05, 'mobile-webgpu': 0.035 },
  }),
  impactSparkLifeSeconds: num({
    owner: 'rendering',
    unit: 'seconds',
    doc: 'Lifetime of an impact spark before it fades out and is recycled — short-lived flash (T80/V57).',
    default: 0.35,
    min: 0.05,
    max: 3,
  }),
  impactSparkSpeedMinMps: num({
    owner: 'rendering',
    unit: 'metersPerSecond',
    doc: 'Minimum launch speed of an impact spark out of the struck surface (T80/V57).',
    default: 4,
    min: 0,
    max: 60,
  }),
  impactSparkSpeedMaxMps: num({
    owner: 'rendering',
    unit: 'metersPerSecond',
    doc: 'Maximum launch speed of an impact spark out of the struck surface (T80/V57).',
    default: 11,
    min: 0,
    max: 80,
  }),
  impactSparkSpreadRad: num({
    owner: 'rendering',
    unit: 'radians',
    doc: 'Cone half-angle around the surface normal within which sparks are scattered (T80/V57).',
    default: 1.0,
    min: 0,
    max: 1.57,
  }),
  impactSparkGravityMps2: num({
    owner: 'rendering',
    unit: 'metersPerSecond',
    doc: 'Downward acceleration on airborne impact sparks so the burst arcs and falls (T80/V57).',
    default: 14,
    min: 0,
    max: 60,
  }),
  impactSparkDragPerSecond: num({
    owner: 'rendering',
    unit: 'ratio',
    doc: 'Speed shed per second by airborne sparks so the burst decelerates (T80/V57).',
    default: 6,
    min: 0,
    max: 30,
  }),
  impactSparkColorR: num({
    owner: 'rendering',
    unit: 'ratio',
    doc: 'Red channel of the bright impact-spark colour — a hot yellow-white, deliberately NON-RED so a wall hit never reads as blood (T80/V57).',
    default: 1,
    min: 0,
    max: 1,
  }),
  impactSparkColorG: num({
    owner: 'rendering',
    unit: 'ratio',
    doc: 'Green channel of the bright impact-spark colour (yellow-white, NON-RED) (T80/V57).',
    default: 0.82,
    min: 0,
    max: 1,
  }),
  impactSparkColorB: num({
    owner: 'rendering',
    unit: 'ratio',
    doc: 'Blue channel of the bright impact-spark colour (yellow-white, NON-RED) (T80/V57).',
    default: 0.4,
    min: 0,
    max: 1,
  }),
  // ---- T108 glass-shard burst (a window pane shattering — pale faceted shards thrown off the wall) ----
  impactShardPoolSize: num({
    owner: 'rendering',
    unit: 'count',
    doc: 'Hard cap on live glass-shard particles across all window smashes (T108). Compacted pool, swap-removed on expiry (V24).',
    default: 192,
    min: 8,
    max: 2048,
    integer: true,
    tiers: { 'desktop-high': 288, 'desktop-compat': 96, 'mobile-webgpu': 48 },
  }),
  impactShardCount: num({
    owner: 'rendering',
    unit: 'count',
    doc: 'Shards thrown per window smash (T108).',
    default: 14,
    min: 1,
    max: 64,
    integer: true,
    tiers: { 'desktop-compat': 9, 'mobile-webgpu': 6 },
  }),
  impactShardSizeMeters: num({
    owner: 'rendering',
    unit: 'meters',
    doc: 'Base edge size of a glass shard (jittered per shard) (T108).',
    default: 0.06,
    min: 0.01,
    max: 0.3,
  }),
  impactShardLifeSeconds: num({
    owner: 'rendering',
    unit: 'seconds',
    doc: 'Base lifetime of a glass shard before it shrinks away (jittered per shard) (T108).',
    default: 0.9,
    min: 0.1,
    max: 4,
  }),
  impactShardSpeedMinMps: num({
    owner: 'rendering',
    unit: 'metersPerSecond',
    doc: 'Min launch speed of a glass shard off the pane (T108).',
    default: 1.4,
    min: 0,
    max: 30,
  }),
  impactShardSpeedMaxMps: num({
    owner: 'rendering',
    unit: 'metersPerSecond',
    doc: 'Max launch speed of a glass shard off the pane (T108).',
    default: 4.2,
    min: 0,
    max: 60,
  }),
  impactShardSpreadRad: num({
    owner: 'rendering',
    unit: 'radians',
    doc: 'Half-angle of the cone the shards scatter into, off the pane normal (T108).',
    default: 1.15,
    min: 0,
    max: 3.14159,
  }),
  impactShardGravityMps2: num({
    owner: 'rendering',
    unit: 'metersPerSecond',
    doc: 'Downward acceleration on a glass shard so it arcs + falls (T108).',
    default: 9.0,
    min: 0,
    max: 40,
  }),
  impactShardSpinMaxRadPerSec: num({
    owner: 'rendering',
    unit: 'radians',
    doc: 'Max tumble angular speed of a glass shard (each gets a random axis + speed up to this) (T108).',
    default: 14,
    min: 0,
    max: 80,
  }),
  impactShardColorR: num({ owner: 'rendering', unit: 'ratio', doc: 'Red of the pale glass-shard tint (cool blue-white, T108).', default: 0.78, min: 0, max: 1 }),
  impactShardColorG: num({ owner: 'rendering', unit: 'ratio', doc: 'Green of the pale glass-shard tint (T108).', default: 0.9, min: 0, max: 1 }),
  impactShardColorB: num({ owner: 'rendering', unit: 'ratio', doc: 'Blue of the pale glass-shard tint (T108).', default: 0.96, min: 0, max: 1 }),
  impactHolePoolSize: num({
    owner: 'rendering',
    unit: 'count',
    doc: 'Hard cap on persistent bullet-hole decals on structures (T80/V57). Ring buffer — oldest recycled past the cap (V24).',
    default: 192,
    min: 8,
    max: 2048,
    integer: true,
    tiers: { 'desktop-high': 288, 'desktop-compat': 96, 'mobile-webgpu': 48 },
  }),
  impactHoleSizeMeters: num({
    owner: 'rendering',
    unit: 'meters',
    doc: 'Diameter of a bullet-hole decal disc projected on the struck surface (T80/V57).',
    default: 0.13,
    min: 0.02,
    max: 1,
    tiers: { 'desktop-high': 0.15, 'mobile-webgpu': 0.11 },
  }),
  impactHoleLifeSeconds: num({
    owner: 'rendering',
    unit: 'seconds',
    doc: 'How long a bullet hole persists before a gentle end-of-life fade and ring-buffer recycle — long-lived, far longer than a spark (T80/V57).',
    default: 60,
    min: 1,
    max: 240,
    tiers: { 'desktop-high': 90, 'mobile-webgpu': 35 },
  }),
  impactHoleFadeFraction: num({
    owner: 'rendering',
    unit: 'ratio',
    doc: 'Final fraction of a bullet-hole lifetime spent shrinking/fading out before the ring buffer recycles it (T80/V57).',
    default: 0.15,
    min: 0.01,
    max: 1,
  }),
  impactWoundPoolSize: num({
    owner: 'rendering',
    unit: 'count',
    doc: 'Hard cap on accumulated wound decals on bodies (zombie + player) (T81/V57). Ring buffer — oldest recycled past the cap (V24).',
    default: 160,
    min: 8,
    max: 2048,
    integer: true,
    tiers: { 'desktop-high': 240, 'desktop-compat': 80, 'mobile-webgpu': 48 },
  }),
  impactWoundSizeMeters: num({
    owner: 'rendering',
    unit: 'meters',
    doc: 'Diameter of a dark wound mark stamped at the struck region of a body (T81/V57).',
    default: 0.16,
    min: 0.02,
    max: 1,
    tiers: { 'desktop-high': 0.18, 'mobile-webgpu': 0.13 },
  }),
  impactWoundLifeSeconds: num({
    owner: 'rendering',
    unit: 'seconds',
    doc: 'How long a wound mark lingers on a body before fading out and recycling (T81/V57).',
    default: 45,
    min: 1,
    max: 240,
    tiers: { 'desktop-high': 60, 'mobile-webgpu': 30 },
  }),
  impactWoundFadeFraction: num({
    owner: 'rendering',
    unit: 'ratio',
    doc: 'Final fraction of a wound-mark lifetime spent fading out before the ring buffer recycles it (T81/V57).',
    default: 0.25,
    min: 0.01,
    max: 1,
  }),
  impactWoundBodyRadiusMeters: num({
    owner: 'rendering',
    unit: 'meters',
    doc: 'Surface offset of a body wound mark from the struck body axis, toward the shooter — sized to hug the thin zombie limb so the mark sits ON the mesh (and is reprojected to the body each frame, so it follows the moving body instead of floating where it was hit) (T81/V57).',
    default: 0.16,
    min: 0.03,
    max: 1,
  }),
};
